# Generated by Django 5.0 on 2024-07-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=None)),
                ('writer', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Headline', models.CharField(max_length=100)),
                ('info', models.TextField()),
            ],
        ),
    ]
